FROM kalilinux/kali-linux-docker

MAINTAINER Mickey

RUN apt-get update -y
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y curl
RUN apt-get install -y wget
RUN apt-get install -y make
RUN apt-get install -y unrar
RUN apt-get install -y sudo
RUN apt-get install -y git
RUN apt-get install -y nano
RUN apt-get install -y zsh
RUN apt-get install -y nmap
RUN apt-get install -y postgresql